# Generated by Django 5.0.7 on 2024-08-04 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_skills_skills_percent_alter_intro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='percentage',
            field=models.ManyToManyField(to='common.skills_percent', verbose_name='percent'),
        ),
        migrations.RemoveField(
            model_name='skills',
            name='language',
        ),
        migrations.AddField(
            model_name='skills',
            name='language',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
