# Generated by Django 5.0.7 on 2024-08-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_skills_percentage_remove_skills_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='skills',
        ),
    ]
