# Generated by Django 5.0.7 on 2024-08-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='date'),
        ),
    ]
