# Generated by Django 5.0.7 on 2024-08-06 09:30

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_portfolio_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thoughts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('text', models.TextField(verbose_name='text')),
                ('image', models.ImageField(upload_to=None, verbose_name='image')),
            ],
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[350, 219], upload_to=None),
        ),
    ]
