# Generated by Django 5.0.7 on 2024-08-06 09:46

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_thoughts_alter_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoughts',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[150, 150], upload_to=None),
        ),
    ]
