# Generated by Django 5.0.7 on 2024-08-06 10:35

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_alter_thoughts_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250, verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('duration', models.DurationField(verbose_name='duration')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[348, 232], upload_to=None)),
                ('image_main', models.ImageField(upload_to=None, verbose_name='image_main')),
                ('category', models.ManyToManyField(related_name='projects', to='common.blogcategory', verbose_name='category')),
            ],
        ),
    ]
