# Generated by Django 5.0.7 on 2024-08-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_blog_content'),
        ('common', '0016_contact_blog_content_blogcomment'),
    ]

    operations = [
    ]
