# Generated by Django 5.0.7 on 2024-08-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_merge_20240807_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('location', models.CharField(max_length=250, verbose_name='location')),
                ('number', models.CharField(max_length=256)),
                ('contact_email', models.EmailField(max_length=254, verbose_name='email')),
            ],
        ),
    ]
